### ISSUE TITLE
Variadic macros used in manner not compliant with ISO C++11

### ISSUE THREAD

**Issue by judemille** [jeremy-rifkin/cpptrace#107] opened 2024-03-21 18:38 UTC
Compiling with `-Wpedantic` reveals a significant number of warnings surrounding the use of the assertion macros in `utils/error.hpp`. It seems that invoking such a macro without at least one argument for the `...` is a violation of ISO C++11. It makes sense to me.

I can submit a PR to separate these macros out into versions with and without messages attached to them.

**Comment by jeremy-rifkin** [comment] 2024-03-21 18:58
Hi,
For any internal library code that is never included into end-user code I haven’t been concerned with -Wpedantic. The reason being that I don’t think users FetchContnet’ing the library probably shouldn’t be imposing the flag on the library target.

However, if this is the only thing, or one of few things, in the library that doesn’t get along with -Wpedantic and it would make a big difference for you I’d be happy to merge a PR.

**Comment by marlowa** [comment] 2024-04-28 10:01
I'd like to see this addressed in the cpptrace header please. Use of the pedantic flag opens one up to issues like this where it is desirable to see pedantic warnings in a project but we get distractions from pedantic warnings in third party headers. It's worse when one is trying to clean up a codebase and have the pedantic warnings treated as errors because it means the project fails to build even though the code of the project itself might be ok.

**Comment by jeremy-rifkin** [comment] 2024-04-29 05:04
If this is affecting multiple users then it's reasonable to try to resolve and support. I can try to resolve this since I haven't heard back from OP.

@marlowa Are you seeing pedantic warnings in cpptrace public-facing headers? (i.e. cpptrace.hpp and ctrace.h) If so, what compiler are you using? I wasn't able to reproduce any with a brief test https://godbolt.org/z/Tnj1G3Wbz.

**Closed** 2024-05-24 02:19 UTC
Labels: question
