### ISSUE TITLE
How to display a saved stack trace ?

### ISSUE THREAD

**Issue by bananasmoothii** [jeremy-rifkin/cpptrace#26] opened 2023-08-21 19:05 UTC
So I was creating my own exception that saves the trace given by `cpptrace::generate_trace()`, but I don't want to display the trace if the exception is catched. How do I print the trace I saved ?

**Comment by jeremy-rifkin** [comment] 2023-08-22 04:52
Hi! Thank you for opening this issue. At the moment the solution is to manually print from the `generate_trace` output however I have been meaning to make the library's interface better here.

**Comment by till213** [comment] 2023-08-22 19:03
> How do I print the trace I saved ?

Hi @bananasmoothii, have a look at my initial implemenation here, written for a Qt application:

https://github.com/till213/SkyDolly/blob/0.16.0/src/Kernel/src/StackTrace_Cpptrace.cpp

It has been shamelessly inspired by Cpptrace's own implementation of cpptrace::print_trace(), so it is essentially a straight-forward translation from pure C++ to Qt's QTextStream.

Please note the branch v0.16: in fact, my implementation has not yet been merged into my own main branch , as this is very much "work in progress" (but if you follow the above link you will have no problems finding my implementation).

My own code is under MIT license, so feel free to "get inspired" :)

**Comment by bananasmoothii** [comment] 2023-08-22 19:35
Thanks !
Currently I pretty much copied and hacked in some non exposed functions (for example `n_digits`):

https://github.com/bananasmoothii/Power4/blob/c39a08b60fef0d34254f351d51ee97db601d0424/src/util/TracedException.hpp

I'd be happy to replace that ugly code by something better, feel free to ping me when you implement this

**Comment by jeremy-rifkin** [comment] 2023-08-22 23:06
Will do, thanks both :)

**Comment by jeremy-rifkin** [comment] 2023-09-19 00:40
Hey folks @till213 @bananasmoothii, I've overhauled the API for the library in #37 and you can now print saved stack traces with `auto trace = cpptrace::generate_trace(); trace.print();`, or alternatively you can create a lightweight trace and resolve and print later `auto trace = cpptrace::generate_raw_trace(); trace.resolve().print();`.

Hope this suits your needs! Let me know if there are any more pain-points in the library. I'll be working towards a new release of the library that will have these changes. At the moment `main` should be stable but I'm trying to test more before releasing, a lot has been changed behind the scenes.

**Closed by jeremy-rifkin** 2023-09-19 00:40 UTC
Labels: library interface

**Comment by till213** [comment] 2023-09-20 17:19
Hello @jeremy-rifkin, that sounds promising! I think @bananasmoothii 's request was to be able to "print a stack trace to a std::string", to be able to process the "formatted stack trace" ourselves (e.g. show it in some widget instead of on std::cout).

Is this what ["generate](cpptrace::generate_raw_trace())](cpptrace::generate_raw_trace()) would do? In any case, for me there is no real need for this just now, because as mentioned earlier I quickly wrote my own "stack trace formatting" function ("printing to a QString" in my case).

"Unfortunately" my own users haven't yet seen your generated stack trace, as my application did not throw any exceptions just yet ;) (I was investigating an "app won't launch on Windows 11, without any error message"-issue - the user was able to "resolve" the issue by temporarily turning "Windows 8" on and then off again, go figure... and my app still wouldn't throw any kind of exception, indicating that it would not even be started at all by Windows - but that's another story anyway).

I did stumble over some very small issue related to checking out with your suggested method of

```
FetchContent_Declare(
  cpptrace
  GIT_REPOSITORY https://github.com/jeremy-rifkin/cpptrace.git
  GIT_TAG        v0.2.0-beta # <HASH or TAG>
)
```

(btw. the CMake documetnation suggests to prefer hashes over tasgs, in order to guarantee "stable builds" - because tags "may be moved to other commits").

The issue is related to "git detached HEAD": this per se is nothing bad (it just means that a previous commit other than the HEAD of the given branch was checked out). However I remember that further down the "CMake compilation chain" this then caused some other step to fail.

Anyway, only a minor point and I will create a separate issue once I get to it: I will extend my https://github.com/till213/CpptraceTest example app accordingly and let you know once done.

Thanks again for your great and very helpful work!

**Comment by jeremy-rifkin** [comment] 2023-09-20 18:18
> Hello @jeremy-rifkin, that sounds promising! I think @bananasmoothii 's request was to be able to "print a stack trace to a std::string", to be able to process the "formatted stack trace" ourselves (e.g. show it in some widget instead of on std::cout).
> 
> UPDATE: Sorry, I just realised that the original request was really just to "print the stack trace" (one that has been captured previously). But still, I believe some "stack trace to std::string" functionality would still be useful ;)

I have you covered, `stacktrace::to_string()` exists now too :)
`cpptrace::generate_trace()` give you a `stacktrace` object with all the frames and a few helper methods. I'm also going to add overloads for `operator<<(ostream)` and an std::formatter specialization for c++20 std::format use.

By the way, I also added a traced exception object `cpptrace::exception` that automatically embeds a stack trace when you throw it.

Thank you for the heads up about hashes over tags, I'll look into this more.

**Comment by till213** [comment] 2023-09-20 19:01
"By the way, I also added a traced exception object cpptrace::exception that automatically embeds a stack trace when you throw it."

Wow, that gets even better! In my case I was chasing a (suspected) exception that would be thrown from "someone else" (= not my code). Again, that did not seem to happen with my "won't launch on Windows11"-case.

But I expect that most people would be interested in their _own_ exceptions and "from where they come from", so your cpptrace::exception is most welcome in those cases!

**Comment by bananasmoothii** [comment] 2023-09-20 19:41
(I use Rust now, it is 100 times better for everything including stack traces)

**Comment by till213** [comment] 2023-10-15 19:19
> that should be part of the language itself

@bananasmoothii , just in case you've missed the memo: as also written in the README of this cpptrace library generating a stack trace actually is part of C++23:

https://en.cppreference.com/w/cpp/utility/basic_stacktrace

;)

However depending on your compiler it may take a while until it will become available:

https://en.cppreference.com/w/cpp/compiler_support/23

At the time of this writing this essentially means:

- GCC libstdc++
- MSVC STL

But since you're now using Rust this is just FYI (and whoever else might stumble over this issue in the future) ;)
